### ISSUE TITLE
Make the "Deploy to OpenShift" command more discoverable

### ISSUE THREAD

**Issue by fbricon** [xorye/vscode-quarkus#406]
Today, only people who know the "Deploy to OpenShift"  command exist will be able to use it. We need to figure out a way to make it more obvious

**Comment by rgrunber** [comment]
Currently, we only generate a notification when a user debugs a Quarkus application, and only the first time, so very limited.

A few places we could put this :

- `contributes/menus/editor/title` should be able to accept a command contribution (with icon) right beside the Run (play button) icon.
- [`contributes/menus/editor/title/run`](https://github.com/microsoft/vscode-java-debug/blob/main/package.json#L186-L197). In the editor title where the Run icon appears (top right)
- [`contributes/menus/{explorer,editor/context}`](https://github.com/microsoft/vscode-java-debug/blob/main/package.json#L162-L185). Context menus when Java source file is present in Explorer or Editor.

**Comment by alejandro-du** [comment]
How can I hide the icon though?

**Comment by rgrunber** [comment]
> How can I hide the icon though?

Currently it isn't possible to hide this. The icon should only show up in a Java source file when a Quarkus project is detected. I noticed we don't check whether vscode-openshift is installed but the icon does prompt to handle that if clicked.

@fbricon , is it worth having a setting just to disable the icon ?

The only other options I can think of are :

1. The icon should only appear if the openshift connector is already installed. Currently we don't check that because clicking the icon triggers a prompt asking whether installation should happen
2. Add a 3rd option (in addition to `Yes`, `No`) called `Never`, which never prompts again to install the connector, and additionally ensures the icon doesn't show up again for the given instance.
