### ISSUE TITLE
Provide HTML support for Qute HTML templates

### ISSUE THREAD

**Issue by fbricon** [xorye/vscode-quarkus#483]
Currently, Qute html templates only get Qute support. HTML validation and completion are missing. Would be nice if we could hook up the HTML LS to qute-html templates.

**Comment by angelozerr** [comment]
I have created the issue https://github.com/microsoft/vscode/issues/131531#

But it will be not perfect because we will have html completion in qute expression.

Is it really annoying?

An another solution is to create a custom langage server which managés html by using vscode html kanguage service. I fera that it us à big work.

If the first solution can be acceptable I will try to create a pr in vscode

**Comment by angelozerr** [comment]
I created a PR in vscode https://github.com/microsoft/vscode/pull/146731

Let's wait feedback.

**Comment by angelozerr** [comment]
My PR from vscode https://github.com/microsoft/vscode/pull/146731 has been merged!

For the moment VSCode Insiders doesn't contains this feature. I'm wiating for that to test my draft PR https://github.com/redhat-developer/vscode-quarkus/pull/527
