### ISSUE TITLE
Message: Request qute/java/documentLink failed with message: Cannot invoke "org.eclipse.jdt.core.dom.ITypeBinding.getQualifiedName()" 

### ISSUE THREAD

**Issue by burrsutter** [xorye/vscode-quarkus#839]
Message: Request qute/java/documentLink failed with message: Cannot invoke "org.eclipse.jdt.core.dom.ITypeBinding.getQualifiedName()" because the return value of "org.eclipse.jdt.core.dom.SimpleType.resolveBinding()" is null
  Code: -32603 

Quarkus extension version: v1.18.1
Tools for MicroProfile v0.12.0

Project https://github.com/burrsutter/ai-rubric

Error seems to show up upon save (Cmd-S)

**Comment by burrsutter** [comment]
<img width="1566" alt="Screenshot 2024-09-19 at 8 25 17 AM" src="https://github.com/user-attachments/assets/10c0437b-177e-456a-bc0f-90e025f1c87c">

**Comment by angelozerr** [comment]
This ugly bug has been fixed with https://github.com/redhat-developer/quarkus-ls/pull/996 and fix are aivailable if you install prerelease of vscode-microprofile and vscode-quarkus.

It seems @burrsutter have no probrem after those prerelease installation.

Thanks @burrsutter for having reported the issue and test prerelease.
